site_name: Thai EV
theme:
  name: material
  palette:
    primary: white
  logo: logo.png
  favicon: favicon.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
nav:
  - Overview: index.md
  - Master Data:
      - Contacts: 1_master_data/1_contact.md
      - Products: 1_master_data/2_product.md
      - Product Category: 1_master_data/3_product_cate.md
      - Chart of Account: 1_master_data/4_coa.md
  - Sales:
      - Overview: 2_sale/1_overview.md
      - Sales: 2_sale/2_sale.md
  - Purchases:
      - Overview: 3_purchase/1_overview.md
      - User: 3_purchase/2_user.md
      - Purchases: 3_purchase/3_purchases.md
  - Inventory:
      - Overview: 4_inventory/1_overview.md
      - Stock In: 4_inventory/2_stock-in.md
      - Stock Out: 4_inventory/3_stock-out.md     
  - Accounting:
      - Overview: 5_accounting/1_overview.md
      - Accounting: 5_accounting/2_accounting.md
  - Approval:
      - Overview: 6_approval/1_overview.md
      - Approver: 6_approval/2_approver.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
