site_name: Thai EV
theme:
  name: material
  palette:
    primary: white
  logo: logo.png
  favicon: favicon.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
nav:
  - Overview: 
      - TEV Overview: 0_overview/overview.md
      - Basic Features: 0_overview/features.md
  - Master Data:
      - Chart of Accounts: 1_master_data/1_coa.md
      - Contacts: 1_master_data/2_contact.md
      - Product Categories: 1_master_data/3_product_cate.md
      - Products: 1_master_data/4_product.md
      - Currencies: 1_master_data/5_currencies.md
  - Sales:
      - Overview: 2_sale/1_overview.md
      - Sales Process: 2_sale/2_sale.md
  - Purchases:
      - Overview: 3_purchase/1_overview.md
      - Purchase Request: 3_purchase/2_user.md
      - Purchase Order: 3_purchase/3_purchase.md
  - Inventory:
      - Overview: 4_inventory/1_overview.md
      - Store: 4_inventory/2_stock.md    
  - Accounting:
      - Overview: 5_accounting/1_overview.md
      - Accounting: 5_accounting/2_accounting.md
  - Approval:
      - Overview: 6_approval/1_overview.md
      - Approver: 6_approval/2_approver.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde