site_name: Thai EV
theme:
  name: material
  palette:
    primary: white
  logo: logo.png
  favicon: favicon.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
nav:
  - Overview: 
      - TEV Overview: index.md
      - Basic Features: 0_overview/features.md
  - Master Data:
      - Chart of Accounts: 1_master_data/1_coa.md
      - Bank: 1_master_data/2_bank.md
      - Journals: 1_master_data/3_journal.md
      - Contacts: 1_master_data/4_contact.md
      - Product Categories: 1_master_data/5_product_cate.md
      - Products: 1_master_data/6_product.md
      - Currencies: 1_master_data/7_currencies.md
      - Users: 1_master_data/8_user.md
  - Sales:
      - Overview: 2_sale/1_overview.md
      - Sales Process: 2_sale/2_sale.md
  - Purchases:
      - Overview: 3_purchase/1_overview.md
      - Purchase Request: 3_purchase/2_user.md
      - Purchase Order: 3_purchase/3_purchase.md
  - Inventory:
      - Overview: 4_inventory/1_overview.md
      - Store: 4_inventory/2_stock.md    
      - Reporting: 4_inventory/3_stock report.md
  - Accounting:
      - Overview: 5_accounting/1_overview.md
      - Accounting: 5_accounting/2_accounting.md
      - Reporting: 5_accounting/3_acc_report.md
  - Approval:
      - Overview: 6_approval/1_overview.md
      - Approver: 6_approval/2_approver.md
  - Other: 
      - Change Password: 7_other/1_change_password.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde